apiVersion: v1
kind: ConfigMap
metadata:
  name: install-gvisor-script
data:
  install.sh: |-
    #!/bin/sh

    BIN_TARGET_DIR=/var/bin/containerruntime/gvisor

    echo "Creating container-runtime binary folder if not exist"
    mkdir -p $BIN_TARGET_DIR

    echo "Copy GVisor Binaries"
    cd /var/content
        chmod +x runsc
        mv runsc /var/host/$BIN_TARGET_DIR
        chmod +x containerd-shim-runsc-v1.linux-amd64
        mv containerd-shim-runsc-v1.linux-amd64  containerd-shim-runsc-v1
        mv containerd-shim-runsc-v1 /var/host/$BIN_TARGET_DIR

    echo "Configure ContainerD"
    then
      echo "[plugins.cri.containerd.runtimes.runsc]
        runtime_type = \"io.containerd.runsc.v1\"" >> /var/host/etc/containerd/config.toml

      chroot /var/host bash -c "systemctl daemon-reload && systemctl reload containerd"
    fi

    echo "Task completed, sleeping"
    while true; do
    	sleep 3600;
    done